### ISSUE TITLE
Exception when called GetMediaListAsync method

### ISSUE THREAD

**Issue by tomasrada** [solrevdev/instagram-basic-display#4]
Solrevdev.InstagramBasicDisplay.Core.Exceptions.InstagramApiException: Syntax error "Expected "(" instead of ","." at character 86: caption,id,media_type,media_url,permalink,thumbnail_url,username,timestamp,children.id,children.media_type,children.media_url,children.permalink,children.thumbnail_url,children.username,children.timestamp
   at Solrevdev.InstagramBasicDisplay.Core.Extensions.HttpResponseMessageExtensions.EnsureSuccessStatusCodeAsync(HttpResponseMessage response)
   at Solrevdev.InstagramBasicDisplay.Core.InstagramHttpClient.GetJsonAsync[T](String url)
   at Solrevdev.InstagramBasicDisplay.Core.InstagramApi.GetMediaListAsync(String accessToken, String userId)

when call GetMediaListAsync method 

this line:
`var url = $"https://graph.instagram.com/{userId}/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,username,timestamp,children.id,children.media_type,children.media_url,children.permalink,children.thumbnail_url,children.username,children.timestamp&access_token={accessToken}";`

should be:
`var url = $"https://graph.instagram.com/{userId}/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,username,timestamp,children{{id,media_type,media_url,permalink,thumbnail_url,username,timestamp}}&access_token={accessToken}";`

**Comment by solrevdev** [comment]
Thanks @tomasrada !

Yes, I spotted that this morning and came to the same conclusion. I think Instagram (or Facebook who knows) have changed the API as that way of calling it did used to work. 

I am happy to accept a pull request if it's super urgent and the GitHub actions will push the change through to NuGet otherwise I will fix later today and push tonight/tomorrow morning. It's 1pm UK time btw.  

I will update here when done

**Comment by solrevdev** [comment]
The latest code changes have been published to nuget. it is still being indexed but here it is 

https://www.nuget.org/packages/Solrevdev.InstagramBasicDisplay/1.0.9
